Lint/EmptyFile:
  Exclude:

Metrics:
  Exclude:
    - 'bin/bundle'
    - 'spec/**/*'
    - 'test/**/*'
    - 'bin/**/*'
    - 'db/**/*'

Metrics/BlockLength:
  Max: 133
  Exclude:
    - 'bin/bundle'
    - 'spec/**/*'
    - 'test/**/*'
    - 'bin/**/*'
    - 'db/**/*'

# Offense count: 1
# Configuration parameters: IgnoredMethods.
Metrics/CyclomaticComplexity:
  Max: 9

# Offense count: 2
# Configuration parameters: CountComments, CountAsOne, ExcludedMethods, IgnoredMethods.
Metrics/MethodLength:
  Max: 12

# Offense count: 1
# Configuration parameters: IgnoredMethods.
Metrics/PerceivedComplexity:
  Max: 9

# Offense count: 1
# Configuration parameters: NamePrefix, ForbiddenPrefixes, AllowedMethods, MethodDefinitionMacros.
# NamePrefix: is_, has_, have_
# ForbiddenPrefixes: is_, has_, have_
# AllowedMethods: is_a?
# MethodDefinitionMacros: define_method, define_singleton_method
Naming/PredicateName:
  Exclude:
    - 'spec/**/*'
    # - 'app/controllers/orders_controller.rb'

# Offense count: 8
# Configuration parameters: AllowedConstants.
Style:
  Exclude:
    - 'bin/bundle'
    - 'spec/**/*'
    - 'test/**/*'
    - 'bin/**/*'
    - 'db/**/*'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'bin/**/*'
    - 'db/**/*'
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Style/IfUnlessModifier:
  Exclude:
    - 'bin/bundle'
# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https

Layout:
  Exclude:
    - 'bin/bundle'
    - 'spec/**/*'
    - 'test/**/*'
    - 'bin/**/*'
    - 'db/**/*'

Layout/LineLength:
  Max: 200

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/ClassAndModuleChildren:
  Enabled: false
